### ISSUE TITLE
Prompts not working in Obsidian 1.7.2 and newer (in certain circumstances related to "Custom variables" view)

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#433]
If you have Obsidian 1.7.2 (or newer) and Shell commands 0.22.0 (or older), the following functionalities may have stopped working:
Assigning values to custom variables:
- **Inputting values via [Prompts](https://publish.obsidian.md/shellcommands/Preactions/Prompts).**
- Assigning values via [Shell commands URI](https://publish.obsidian.md/shellcommands/Basic+usage/Shell+commands+URI).
- Assigning valuea via [an output channel](https://publish.obsidian.md/shellcommands/Output+handling/Output+channel+-+Assign+custom+variables).

Settings:
- [Creating new custom variables](https://publish.obsidian.md/shellcommands/Variables/Custom+variables#How+to+create+custom+variables).
- Changing a custom variable's name, description or [default value](https://publish.obsidian.md/shellcommands/Variables/Default+values).
- Deleting a custom variable.

I did not try all of these, but looking at the source code those looked like features that could be broken.

## What happens

For example, when inputting values into a prompt and then trying to execute a shell command, nothing happens when the Execute button is clicked or when hitting the Enter key. If you hit Ctrl + Shift + I you can see the following error in console:
![kuva](https://github.com/user-attachments/assets/3b1bdf08-62a8-4e10-b3ef-a3a260680356)

## What has changed in Obsidian

From the release notes of [Obsidian 1.7.2](https://obsidian.md/changelog/2024-09-19-desktop-v1.7.2/):

> Views now load only when visible, improving startup performance and memory usage. This might cause issues with some plugins, but we've published [a guide](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views) for plugin developers.

Every time changes are done to custom variable(s), the SC plugin tries to update the contents of a [Custom variable view](https://publish.obsidian.md/shellcommands/Variables/Custom+variables#Monitor+the+custom+variable+values).

If the Custom variable view is not open, Obsidian 1.7.2 (and newer) will no more give the view to SC - instead it gives a [DeferredView](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views), which SC doesn't understand, and causes an error. This error stops further actions of the SC plugin, e.g. executing a shell command.

## Temporary workaround before a final fix

You can [open up the Custom variable view](https://publish.obsidian.md/shellcommands/Variables/Custom+variables#Monitor+the+custom+variable+values) and then minimize the side pane or switch to another pane. If the problem repeats, try to keep the view open all the time.

The bug will be permanently fixed in SC `0.23.0`.

## TODO

- [x] Fix the problem.
- [x] Mention in CHANGELOG.md.
- [x] Mention in documentation (prompts page, custom variables page at least).

**Comment by Taitava** [comment]
Now I figured out why the problem does not occur all the time.

- If "Custom variables" view has never been opened -> the problem does not occur.
- If the view has been opened earlier and its hidden in the sidebar when Obsidian starts (either the sibar is hidden, or some other view is open in the sidebar) -> the problem does occur.
- Opening the view prevents the problem from happening again.
- Also, closing the view completely (right click on the view's icon -> close) prevents the problem.

So the key thing here is that if the view **exists** but has not been shown after Obsidian has started, prompts will not work. If the view doesn't exist, or if it has been visible, prompts do work.

**Comment by Taitava** [comment]
Fixed. Will be released in `0.23.0`.
